In [6]:
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.models import Sequential
model = Sequential()
model.add(SimpleRNN(hidden_units))

NameError: name 'hidden_units' is not defined

In [7]:
model.add(SimpleRNN(hidden_units,input_shape=(timesteps,input_dim)))

model.add(SimpleRNN(hidden_units,input_length=M,input_dim=N))

NameError: name 'hidden_units' is not defined

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3,input_shape=(2,10)))
# model.add(SimpleRNN(3, input_length=2, input_dim=10))와 동일함.
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [9]:
model = Sequential()
model.add(SimpleRNN(3,batch_input_shape=(8,2,10)))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (8, 3)                    42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [10]:
model = Sequential()
model.add(SimpleRNN(3,batch_input_shape=(8,2,10),return_sequences=True))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [11]:
hidden_state_t = 0
for input_t in input_length:
    output_t = tanh(input_t,hidden_state_t)
    hidden_state_t = output_t

NameError: name 'input_length' is not defined

In [12]:
import numpy as np
timesteps = 10
input_dim = 4
hidden_units = 8

inputs = np.random.random((timesteps,input_dim))

hidden_state_t = np.zeros((hidden_units,))
print('초기 은닉 상태 :',hidden_state_t)

초기 은닉 상태 : [0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
Wx = np.random.random((hidden_units,input_dim))
Wh = np.random.random((hidden_units,hidden_units))
b= np.random.random((hidden_units,))
print('가중치 Wx의 크기(shape) :',np.shape(Wx))
print('가중치 Wh의 크기(shape) :',np.shape(Wh))
print('편향의 크기(shape) :',np.shape(b))

가중치 Wx의 크기(shape) : (8, 4)
가중치 Wh의 크기(shape) : (8, 8)
편향의 크기(shape) : (8,)


In [14]:
total_hidden_states = []
for input_t in inputs:
    output_t = np.tanh(np.dot(Wx,input_t) + np.dot(Wh,hidden_state_t)+ b)
    
    total_hidden_states.append(list(output_t))
    hidden_state_t = output_t
total_hidden_states = np.stack(total_hidden_states,axis=0)
print('모든 시점의 은닉 상태 :')
print(total_hidden_states)

모든 시점의 은닉 상태 :
[[0.50571797 0.90725626 0.60538131 0.87836761 0.79348502 0.88907921
  0.96058751 0.93614495]
 [0.99996879 0.99992357 0.99969908 0.99997738 0.99965856 0.99986497
  0.999986   0.99996433]
 [0.99997795 0.99996435 0.99987832 0.99999089 0.99980272 0.99993216
  0.99999793 0.99998641]
 [0.99999292 0.99997885 0.99991374 0.99999281 0.99988446 0.99995283
  0.99999822 0.99998914]
 [0.999995   0.99999325 0.99994254 0.99999682 0.99996062 0.99998436
  0.99999933 0.99999485]
 [0.99998903 0.99997969 0.99990816 0.99999658 0.99991577 0.99995229
  0.99999829 0.99999495]
 [0.99997279 0.99987137 0.99982426 0.99997886 0.99953179 0.99985009
  0.99999352 0.99996692]
 [0.99998215 0.99996161 0.9998835  0.99999199 0.99983897 0.99994067
  0.99999756 0.99998737]
 [0.99999261 0.99999531 0.99994133 0.99999788 0.99996145 0.9999818
  0.99999956 0.99999697]
 [0.99999566 0.99999175 0.9999387  0.99999551 0.99994161 0.99997624
  0.99999917 0.99999321]]


In [16]:
model = Sequential()
model.add(SimpleRNN(hidden_units,input_length=10,input_dim=5,return_sequences=True))
model.add(SimpleRNN(hidden_units,return_sequences=True))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_4 (SimpleRNN)     (None, 10, 8)             112       
_________________________________________________________________
simple_rnn_5 (SimpleRNN)     (None, 10, 8)             136       
Total params: 248
Trainable params: 248
Non-trainable params: 0
_________________________________________________________________


In [18]:
from tensorflow.keras.layers import Bidirectional
timesteps = 10
input_dim = 5
model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_units,return_sequences=True),input_shape=(timesteps,input_dim)))

In [20]:
model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_units,return_sequences=True),input_shape=(timesteps,input_dim)))
model.add(Bidirectional(SimpleRNN(hidden_units,return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_units,return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_units,return_sequences=True)))
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_5 (Bidirection (None, 10, 16)            224       
_________________________________________________________________
bidirectional_6 (Bidirection (None, 10, 16)            400       
_________________________________________________________________
bidirectional_7 (Bidirection (None, 10, 16)            400       
_________________________________________________________________
bidirectional_8 (Bidirection (None, 10, 16)            400       
Total params: 1,424
Trainable params: 1,424
Non-trainable params: 0
_________________________________________________________________


In [1]:
# KERAS GRU
model.add(GRU(hidden_size,input_shape=(timesteps,input_dim)))

NameError: name 'model' is not defined

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN,LSTM,Bidirectional

In [3]:
train_X= [[0.1,4.2,1.5,1.1,2.8],[1.0,3.1,2.5,0.7,1.1],[0.3,2.1,1.5,2.1,0.1],[2.2,1.4,0.5,0.9,1.1]]
print(np.shape(train_X))

(4, 5)


In [4]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X,dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [5]:
rnn = SimpleRNN(3)
# rnn = SimpleRNN(3,return_sequences=False, return_state=False)
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state,hidden_state.shape))

hidden state : [[-0.9716032 -0.5257024 -0.9866782]], shape: (1, 3)


In [6]:
rnn = SimpleRNN(3,return_sequences=True)
hidden_states = rnn(train_X)
print('hidden states : {}, shape: {}'.format(hidden_states,hidden_states.shape))

hidden states : [[[-0.59935856  0.9501925  -0.9967708 ]
  [ 0.11284617  0.9931246  -0.9262317 ]
  [ 0.8435606   0.9569659  -0.9552238 ]
  [ 0.93895537  0.9929197  -0.9337937 ]]], shape: (1, 4, 3)


In [8]:
rnn = SimpleRNN(3,return_sequences=True,return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states,hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state,last_state.shape))

hidden states : [[[-0.88198197  0.9999322  -0.99997133]
  [-0.9993907   0.99933    -0.9999045 ]
  [-0.9935954   0.85836935 -0.99845207]
  [-0.9982384   0.60425067 -0.9840131 ]]], shape: (1, 4, 3)
last hidden state : [[-0.9982384   0.60425067 -0.9840131 ]], shape: (1, 3)


In [11]:
rnn = SimpleRNN(3,return_sequences=False,return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_state,hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state,last_state.shape))

hidden states : [[-0.8669409  0.9178482 -0.9846595]], shape: (1, 3)
last hidden state : [[-0.8669409  0.9178482 -0.9846595]], shape: (1, 3)


In [13]:
lstm = LSTM(3,return_sequences=False, return_state=True)
hidden_state , last_state,last_cell_state = lstm(train_X)
print('hidden state : {}, shape: {}'.format(hidden_state,hidden_state.shape))
print('last state : {}, shape: {}'.format(last_state,last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state,last_cell_state.shape))

hidden state : [[ 0.16715123  0.02350286 -0.28459555]], shape: (1, 3)
last state : [[ 0.16715123  0.02350286 -0.28459555]], shape: (1, 3)
last cell state : [[ 0.47846556  0.03586906 -0.81367755]], shape: (1, 3)


In [14]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden states : [[[ 0.00045257  0.20976567 -0.01780145]
  [ 0.05810369 -0.13566414 -0.17132653]
  [ 0.10796597 -0.14652531 -0.36971757]
  [-0.06538382 -0.22209194 -0.45135295]]], shape: (1, 4, 3)
last hidden state : [[-0.06538382 -0.22209194 -0.45135295]], shape: (1, 3)
last cell state : [[-0.13397744 -0.52863    -1.2235613 ]], shape: (1, 3)


In [15]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value = 0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [20]:
bilstm = Bidirectional(LSTM(3,return_sequences=False, return_state=True, \
                           kernel_initializer=k_init, bias_initializer=b_init,recurrent_initializer=r_init))
hidden_state,forward_h,forward_c,backward_h,backward_c = bilstm(train_X)
print('hidden states : {}, shape : {}'.format(hidden_states,hidden_states.shape))
print('forward states : {}, shape :  {}'.format(forward_h,forward_h.shape))
print('backward states : {}, shape :  {}'.format(backward_h,backward_h.shape))

hidden states : [[0.6303138 0.6303138 0.6303138 0.7038734 0.7038734 0.7038734]], shape : (1, 6)
forward states : [[0.6303138 0.6303138 0.6303138]], shape :  (1, 3)
backward states : [[0.7038734 0.7038734 0.7038734]], shape :  (1, 3)


In [21]:
bilstm = Bidirectional(LSTM(3,return_sequences=True,return_state=True,\
                           kernel_initializer=k_init,bias_initializer=b_init,recurrent_initializer=r_init))
hidden_states,forward_h,forward_c,backward_h,backward_c = bilstm(train_X)

In [22]:
print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.55111325 0.55111325 0.55111325 0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.6303138  0.6303138  0.6303138  0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state : [[0.6303138 0.6303138 0.6303138]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [5]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [6]:
text = """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다 \n
가는 말이 고와야 오는 말이 곱다\n"""

In [7]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [8]:
print(tokenizer.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [9]:
sequences = list()
for line in text.split('\n'):
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
print('학습에 사용한 샘플의 개수 : %d'% len(sequences))

학습에 사용한 샘플의 개수 : 11


In [10]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [11]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [12]:
sequences = pad_sequences(sequences,maxlen=max_len, padding='pre')

In [13]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [14]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [15]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [16]:
y = to_categorical(y,num_classes=vocab_size)

In [17]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense,SimpleRNN

In [19]:
embedding_dim = 10
hidden_units = 32
model = Sequential()
model.add(Embedding(vocab_size,embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=200,verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.4821 - accuracy: 0.0909
Epoch 2/200
1/1 - 0s - loss: 2.4676 - accuracy: 0.0909
Epoch 3/200
1/1 - 0s - loss: 2.4535 - accuracy: 0.1818
Epoch 4/200
1/1 - 0s - loss: 2.4397 - accuracy: 0.1818
Epoch 5/200
1/1 - 0s - loss: 2.4259 - accuracy: 0.2727
Epoch 6/200
1/1 - 0s - loss: 2.4121 - accuracy: 0.2727
Epoch 7/200
1/1 - 0s - loss: 2.3982 - accuracy: 0.3636
Epoch 8/200
1/1 - 0s - loss: 2.3841 - accuracy: 0.4545
Epoch 9/200
1/1 - 0s - loss: 2.3695 - accuracy: 0.4545
Epoch 10/200
1/1 - 0s - loss: 2.3545 - accuracy: 0.4545
Epoch 11/200
1/1 - 0s - loss: 2.3389 - accuracy: 0.4545
Epoch 12/200
1/1 - 0s - loss: 2.3226 - accuracy: 0.4545
Epoch 13/200
1/1 - 0s - loss: 2.3054 - accuracy: 0.4545
Epoch 14/200
1/1 - 0s - loss: 2.2875 - accuracy: 0.5455
Epoch 15/200
1/1 - 0s - loss: 2.2686 - accuracy: 0.5455
Epoch 16/200
1/1 - 0s - loss: 2.2487 - accuracy: 0.5455
Epoch 17/200
1/1 - 0s - loss: 2.2278 - accuracy: 0.4545
Epoch 18/200
1/1 - 0s - loss: 2.2058 - accuracy: 0.3636
E

Epoch 147/200
1/1 - 0s - loss: 0.3487 - accuracy: 0.9091
Epoch 148/200
1/1 - 0s - loss: 0.3443 - accuracy: 0.9091
Epoch 149/200
1/1 - 0s - loss: 0.3399 - accuracy: 0.9091
Epoch 150/200
1/1 - 0s - loss: 0.3356 - accuracy: 0.9091
Epoch 151/200
1/1 - 0s - loss: 0.3313 - accuracy: 0.9091
Epoch 152/200
1/1 - 0s - loss: 0.3271 - accuracy: 0.9091
Epoch 153/200
1/1 - 0s - loss: 0.3230 - accuracy: 0.9091
Epoch 154/200
1/1 - 0s - loss: 0.3189 - accuracy: 0.9091
Epoch 155/200
1/1 - 0s - loss: 0.3148 - accuracy: 0.9091
Epoch 156/200
1/1 - 0s - loss: 0.3108 - accuracy: 0.9091
Epoch 157/200
1/1 - 0s - loss: 0.3069 - accuracy: 0.9091
Epoch 158/200
1/1 - 0s - loss: 0.3030 - accuracy: 0.9091
Epoch 159/200
1/1 - 0s - loss: 0.2991 - accuracy: 0.9091
Epoch 160/200
1/1 - 0s - loss: 0.2953 - accuracy: 0.9091
Epoch 161/200
1/1 - 0s - loss: 0.2915 - accuracy: 0.9091
Epoch 162/200
1/1 - 0s - loss: 0.2877 - accuracy: 0.9091
Epoch 163/200
1/1 - 0s - loss: 0.2840 - accuracy: 0.9091
Epoch 164/200
1/1 - 0s - loss: 

In [20]:
def sentence_generation(model,tokenizer,current_word,n):
    init_word = current_word
    sentence = ''
    
    for _ in range(n):
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded],maxlen=5,padding='pre')
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)
        
        for word, index in tokenizer.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    return sentence

In [21]:
print(sentence_generation(model,tokenizer,'경마장에',4))

경마장에 있는 말이 뛰고 있다


In [22]:
print(sentence_generation(model,tokenizer,'그의', 2))

그의 말이 법이다


In [23]:
print(sentence_generation(model,tokenizer,'가는',5))

가는 말이 고와야 오는 말이 곱다


In [24]:
import pandas as pd
import numpy as np
from string import punctuation

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [27]:
df = pd.read_csv('archive (1)/ArticlesApril2018.csv')
df.head()

articleID  articleWordCount  \
0  5adf6684068401528a2aa69b               781   
1  5adf653f068401528a2aa697               656   
2  5adf4626068401528a2aa628              2427   
3  5adf40d2068401528a2aa619               626   
4  5adf3d64068401528a2aa60f               815   

                                      byline documentType  \
0                             By JOHN BRANCH      article   
1                           By LISA FRIEDMAN      article   
2                              By PETE WELLS      article   
3  By JULIE HIRSCHFELD DAVIS and PETER BAKER      article   
4             By IAN AUSTEN and DAN BILEFSKY      article   

                                            headline  \
0  Former N.F.L. Cheerleaders’ Settlement Offer: ...   
1  E.P.A. to Unveil a New Rule. Its Effect: Less ...   
2                            The New Noma, Explained   
3                                            Unknown   
4                                            Unknown   

                                            keywords  multimedia     newDesk  \
0  ['Workplace Hazards and Violations', 'Football...          68      Sports   
1  ['Environmental Protection Agency', 'Pruitt, S...          68     Climate   
2  ['Restaurants', 'Noma (Copenhagen, Restaurant)...          66      Dining   
3  ['Macron, Emmanuel (1977- )', 'Trump, Donald J...          68  Washington   
4  ['Toronto, Ontario, Attack (April, 2018)', 'Mu...          68     Foreign   

   printPage              pubDate   sectionName  \
0          0  2018-04-24 17:16:49  Pro Football   
1          0  2018-04-24 17:11:21       Unknown   
2          0  2018-04-24 14:58:44       Unknown   
3          0  2018-04-24 14:35:57        Europe   
4          0  2018-04-24 14:21:21        Canada   

                                             snippet              source  \
0  “I understand that they could meet with us, pa...  The New York Times   
1  The agency plans to publish a new regulation T...  The New York Times   
2  What’s it like to eat at the second incarnatio...  The New York Times   
3  President Trump welcomed President Emmanuel Ma...  The New York Times   
4  Alek Minassian, 25, a resident of Toronto’s Ri...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2018/04/24/sports/foot...  
1           News  https://www.nytimes.com/2018/04/24/climate/epa...  
2           News  https://www.nytimes.com/2018/04/24/dining/noma...  
3           News  https://www.nytimes.com/2018/04/24/world/europ...  
4           News  https://www.nytimes.com/2018/04/24/world/canad...

In [28]:
print('열의 개수 :',len(df.columns))
print(df.columns)

열의 개수 : 15
Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [29]:
print(df['headline'].isnull().values.any())

False


In [30]:
headline = []
headline.extend(list(df.headline.values))
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [31]:
print('총 샘플의 개수 : {}'.format(len(headline)))

총 샘플의 개수 : 1324


In [32]:
headline = [word for word in headline if word != 'Unknown']
print('노이즈값 제거 후 샘플의 개수 : {}'.format(len(headline)))

노이즈값 제거 후 샘플의 개수 : 1214


In [34]:
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [40]:
def repreprocessing(raw_sentence):
    preprocessed_sentence = raw_sentence.encode('utf8').decode('ascii','ignore')
    return ''.join(word for word in preprocessed_sentence if word not in punctuation).lower()
preprocessed_headline = [repreprocessing(x) for x in headline]
preprocessed_headline[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [41]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_headline)
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 3494


In [42]:
sequences = list()
for sentence in preprocessed_headline:
    encoded = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1,len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [46]:
index_to_word = {}
for key, value in tokenizer.word_index.items():
    index_to_word[value] = key
print('빈도수 상위 582번 단어 : {}'.format(index_to_word[582]))

빈도수 상위 582번 단어 : offer


In [47]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 24


In [48]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [50]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [51]:
print(X[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]


In [52]:
print(y[:3])

[ 269  371 1115]


In [53]:
y = to_categorical(y, num_classes=vocab_size)

In [54]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [55]:
embedding_dim = 10
hidden_units = 128
model = Sequential()
model.add(Embedding(vocab_size,embedding_dim))
model.add(LSTM(hidden_units))
model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=200,verbose=2)

Epoch 1/200
244/244 - 6s - loss: 7.6540 - accuracy: 0.0296
Epoch 2/200
244/244 - 4s - loss: 7.1152 - accuracy: 0.0290
Epoch 3/200
244/244 - 4s - loss: 6.9828 - accuracy: 0.0328
Epoch 4/200
244/244 - 3s - loss: 6.8657 - accuracy: 0.0406
Epoch 5/200
244/244 - 4s - loss: 6.7289 - accuracy: 0.0443
Epoch 6/200
244/244 - 4s - loss: 6.5671 - accuracy: 0.0482
Epoch 7/200
244/244 - 4s - loss: 6.3898 - accuracy: 0.0511
Epoch 8/200
244/244 - 4s - loss: 6.2082 - accuracy: 0.0557
Epoch 9/200
244/244 - 4s - loss: 6.0235 - accuracy: 0.0604
Epoch 10/200
244/244 - 3s - loss: 5.8458 - accuracy: 0.0645
Epoch 11/200
244/244 - 4s - loss: 5.6718 - accuracy: 0.0713
Epoch 12/200
244/244 - 4s - loss: 5.5102 - accuracy: 0.0724
Epoch 13/200
244/244 - 4s - loss: 5.3559 - accuracy: 0.0773
Epoch 14/200
244/244 - 4s - loss: 5.2037 - accuracy: 0.0836
Epoch 15/200
244/244 - 4s - loss: 5.0593 - accuracy: 0.0879
Epoch 16/200
244/244 - 3s - loss: 4.9199 - accuracy: 0.1019
Epoch 17/200
244/244 - 3s - loss: 4.7919 - accura

244/244 - 4s - loss: 0.3395 - accuracy: 0.9155
Epoch 138/200
244/244 - 4s - loss: 0.3388 - accuracy: 0.9171
Epoch 139/200
244/244 - 4s - loss: 0.3392 - accuracy: 0.9145
Epoch 140/200
244/244 - 4s - loss: 0.3328 - accuracy: 0.9162
Epoch 141/200
244/244 - 3s - loss: 0.3269 - accuracy: 0.9153
Epoch 142/200
244/244 - 4s - loss: 0.3209 - accuracy: 0.9167
Epoch 143/200
244/244 - 3s - loss: 0.3195 - accuracy: 0.9166
Epoch 144/200
244/244 - 4s - loss: 0.3163 - accuracy: 0.9166
Epoch 145/200
244/244 - 4s - loss: 0.3129 - accuracy: 0.9180
Epoch 146/200
244/244 - 4s - loss: 0.3102 - accuracy: 0.9167
Epoch 147/200
244/244 - 4s - loss: 0.3084 - accuracy: 0.9164
Epoch 148/200
244/244 - 4s - loss: 0.3168 - accuracy: 0.9146
Epoch 149/200
244/244 - 4s - loss: 0.3239 - accuracy: 0.9140
Epoch 150/200
244/244 - 4s - loss: 0.3221 - accuracy: 0.9150
Epoch 151/200
244/244 - 4s - loss: 0.3020 - accuracy: 0.9179
Epoch 152/200
244/244 - 4s - loss: 0.2974 - accuracy: 0.9175
Epoch 153/200
244/244 - 4s - loss: 0.2

In [65]:
def sentence_generation(model,tokenizer,current_word,n):
    init_word = current_word
    sentence = ''
    
    for _ in range(n):
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded],maxlen=max_len-1,padding='pre')
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result,axis=1)
        
        for word, index in tokenizer.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    return sentence

In [66]:
print(sentence_generation(model,tokenizer,'i',10))

i cant jump ship from facebook yet melania a birthday gift


In [67]:
print(sentence_generation(model,tokenizer,'how',10))

how can a doctor grapple with the epidemic of cost care


In [1]:
import numpy as np
import urllib.request
from tensorflow.keras.utils import to_categorical

urllib.request.urlretrieve("http://www.gutenberg.org/files/11/11-0.txt", filename="11-0.txt")

f = open('11-0.txt','rb')
sentences = []
for sentence in f:
    sentence = sentence.strip()
    sentence = sentence.lower()
    sentence = sentence.decode('ascii','ignore')
    if len(sentence) > 0:
        sentences.append(sentence)
f.close()

In [2]:
sentences[:5]

['the project gutenberg ebook of alices adventures in wonderland, by lewis carroll',
 'this ebook is for the use of anyone anywhere in the united states and',
 'most other parts of the world at no cost and with almost no restrictions',
 'whatsoever. you may copy it, give it away or re-use it under the terms',
 'of the project gutenberg license included with this ebook or online at']

In [5]:
total_data = ' '.join(sentences)
print('문자열의 길이 또는 총 문자의 개수 : %d '% len(total_data))

문자열의 길이 또는 총 문자의 개수 : 159484 


In [4]:
print(total_data[:200])

the project gutenberg ebook of alices adventures in wonderland, by lewis carroll this ebook is for the use of anyone anywhere in the united states and most other parts of the world at no cost and with


In [6]:
char_vocab = sorted(list(set(total_data)))
vocab_size = len(char_vocab)
print('문자 집합의 크기 : {}'.format(vocab_size))

문자 집합의 크기 : 56


In [7]:
char_to_index = dict((char,index) for index,char in enumerate(char_vocab))
print('문자 집합 :',char_to_index)

문자 집합 : {' ': 0, '!': 1, '"': 2, '#': 3, '$': 4, '%': 5, "'": 6, '(': 7, ')': 8, '*': 9, ',': 10, '-': 11, '.': 12, '/': 13, '0': 14, '1': 15, '2': 16, '3': 17, '4': 18, '5': 19, '6': 20, '7': 21, '8': 22, '9': 23, ':': 24, ';': 25, '?': 26, '[': 27, ']': 28, '_': 29, 'a': 30, 'b': 31, 'c': 32, 'd': 33, 'e': 34, 'f': 35, 'g': 36, 'h': 37, 'i': 38, 'j': 39, 'k': 40, 'l': 41, 'm': 42, 'n': 43, 'o': 44, 'p': 45, 'q': 46, 'r': 47, 's': 48, 't': 49, 'u': 50, 'v': 51, 'w': 52, 'x': 53, 'y': 54, 'z': 55}


In [8]:
index_to_char = {}
for key,value in char_to_index.items():
    index_to_char[value] = key

In [9]:
train_X = 'appl'
train_y = 'pple'

In [10]:
seq_length = 60
n_samples = int(np.floor((len(total_data)-1) / seq_length))
print('샘플의 수 : {}'.format(n_samples))

샘플의 수 : 2658


In [11]:
train_X = []
train_y = []
for i in range(n_samples):
    X_sample = total_data[i * seq_length : (i+1) * seq_length]
    
    X_encoded = [char_to_index[c] for c in X_sample]
    train_X.append(X_encoded)
    y_sample = total_data[i * seq_length + 1: (i+1) * seq_length + 1]
    y_encoded = [char_to_index[c] for c in y_sample]
    train_y.append(y_encoded)

In [12]:
print('X 데이터의 첫번째 샘플 :',train_X[0])
print('y 데이터의 첫번째 샘플 :',train_y[0])
print('-'*50)
print("X 데이터의 첫번째 샘플 디코딩 :",[index_to_char[i] for i in train_X[0]])
print("y 데이터의 첫번째 샘플 디코딩 :",[index_to_char[i] for i in train_y[0]])

X 데이터의 첫번째 샘플 : [49, 37, 34, 0, 45, 47, 44, 39, 34, 32, 49, 0, 36, 50, 49, 34, 43, 31, 34, 47, 36, 0, 34, 31, 44, 44, 40, 0, 44, 35, 0, 30, 41, 38, 32, 34, 48, 0, 30, 33, 51, 34, 43, 49, 50, 47, 34, 48, 0, 38, 43, 0, 52, 44, 43, 33, 34, 47, 41, 30]
y 데이터의 첫번째 샘플 : [37, 34, 0, 45, 47, 44, 39, 34, 32, 49, 0, 36, 50, 49, 34, 43, 31, 34, 47, 36, 0, 34, 31, 44, 44, 40, 0, 44, 35, 0, 30, 41, 38, 32, 34, 48, 0, 30, 33, 51, 34, 43, 49, 50, 47, 34, 48, 0, 38, 43, 0, 52, 44, 43, 33, 34, 47, 41, 30, 43]
--------------------------------------------------
X 데이터의 첫번째 샘플 디코딩 : ['t', 'h', 'e', ' ', 'p', 'r', 'o', 'j', 'e', 'c', 't', ' ', 'g', 'u', 't', 'e', 'n', 'b', 'e', 'r', 'g', ' ', 'e', 'b', 'o', 'o', 'k', ' ', 'o', 'f', ' ', 'a', 'l', 'i', 'c', 'e', 's', ' ', 'a', 'd', 'v', 'e', 'n', 't', 'u', 'r', 'e', 's', ' ', 'i', 'n', ' ', 'w', 'o', 'n', 'd', 'e', 'r', 'l', 'a']
y 데이터의 첫번째 샘플 디코딩 : ['h', 'e', ' ', 'p', 'r', 'o', 'j', 'e', 'c', 't', ' ', 'g', 'u', 't', 'e', 'n', 'b', 'e', 'r', 'g', ' ', 'e',

In [13]:
print(train_X[1])

[43, 33, 10, 0, 31, 54, 0, 41, 34, 52, 38, 48, 0, 32, 30, 47, 47, 44, 41, 41, 0, 49, 37, 38, 48, 0, 34, 31, 44, 44, 40, 0, 38, 48, 0, 35, 44, 47, 0, 49, 37, 34, 0, 50, 48, 34, 0, 44, 35, 0, 30, 43, 54, 44, 43, 34, 0, 30, 43, 54]


In [14]:
print(train_y[1])

[33, 10, 0, 31, 54, 0, 41, 34, 52, 38, 48, 0, 32, 30, 47, 47, 44, 41, 41, 0, 49, 37, 38, 48, 0, 34, 31, 44, 44, 40, 0, 38, 48, 0, 35, 44, 47, 0, 49, 37, 34, 0, 50, 48, 34, 0, 44, 35, 0, 30, 43, 54, 44, 43, 34, 0, 30, 43, 54, 52]


In [15]:
train_X = to_categorical(train_X)
train_y = to_categorical(train_y)

print('train_X의 크기(shape) : {}'.format(train_X.shape))
print('train_y의 크기(shape) : {}'.format(train_y.shape))

train_X의 크기(shape) : (2658, 60, 56)
train_y의 크기(shape) : (2658, 60, 56)


In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,TimeDistributed

hidden_units = 256
model = Sequential()
model.add(LSTM(hidden_units,input_shape=(None,train_X.shape[2]),return_sequences=True))
model.add(LSTM(hidden_units, return_sequences=True))
model.add(TimeDistributed(Dense(vocab_size,activation='softmax')))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(train_X,train_y,epochs=80, verbose=2)

Epoch 1/80
84/84 - 24s - loss: 3.0657 - accuracy: 0.1832
Epoch 2/80
84/84 - 19s - loss: 2.7152 - accuracy: 0.2490
Epoch 3/80
84/84 - 19s - loss: 2.3919 - accuracy: 0.3307
Epoch 4/80
84/84 - 18s - loss: 2.2481 - accuracy: 0.3621
Epoch 5/80
84/84 - 18s - loss: 2.1436 - accuracy: 0.3881
Epoch 6/80
84/84 - 18s - loss: 2.0597 - accuracy: 0.4099
Epoch 7/80
84/84 - 18s - loss: 1.9902 - accuracy: 0.4277
Epoch 8/80
84/84 - 19s - loss: 1.9311 - accuracy: 0.4415
Epoch 9/80
84/84 - 18s - loss: 1.8745 - accuracy: 0.4574
Epoch 10/80
84/84 - 18s - loss: 1.8260 - accuracy: 0.4699
Epoch 11/80
84/84 - 18s - loss: 1.7823 - accuracy: 0.4824
Epoch 12/80
84/84 - 18s - loss: 1.7424 - accuracy: 0.4929
Epoch 13/80
84/84 - 18s - loss: 1.7014 - accuracy: 0.5029
Epoch 14/80
84/84 - 18s - loss: 1.6644 - accuracy: 0.5140
Epoch 15/80
84/84 - 18s - loss: 1.6289 - accuracy: 0.5215
Epoch 16/80
84/84 - 17s - loss: 1.5963 - accuracy: 0.5315
Epoch 17/80
84/84 - 17s - loss: 1.5636 - accuracy: 0.5391
Epoch 18/80
84/84 - 17s

In [19]:
def sentence_generation(model, length):
    # 문자에 대한 랜덤한 정수 생성
    ix = [np.random.randint(vocab_size)]

    # 랜덤한 정수로부터 맵핑되는 문자 생성
    y_char = [index_to_char[ix[-1]]]
    print(ix[-1],'번 문자',y_char[-1],'로 예측을 시작!')

    # (1, length, 55) 크기의 X 생성. 즉, LSTM의 입력 시퀀스 생성
    X = np.zeros((1, length, vocab_size))

    for i in range(length):
        # X[0][i][예측한 문자의 인덱스] = 1, 즉, 예측 문자를 다음 입력 시퀀스에 추가
        X[0][i][ix[-1]] = 1
        print(index_to_char[ix[-1]], end="")
        ix = np.argmax(model.predict(X[:, :i+1, :])[0], 1)
        y_char.append(index_to_char[ix[-1]])
    return ('').join(y_char)

In [20]:
result = sentence_generation(model,100)
print(result)

6 번 문자 ' 로 예측을 시작!
's more-tmabber wed, jut it was aspectackest: its electtinal little birds and beasts, as weld be som's more-tmabber wed, jut it was aspectackest: its electtinal little birds and beasts, as weld be some


In [1]:
import numpy as np
from tensorflow.keras.utils import to_categorical

In [2]:
raw_text = '''
I get on with life as a programmer,
I like to contemplate beer.
But when I start to daydream,
My mind turns straight to wine.

Do I love wine more than beer?

I like to use words about beer.
But when I stop my talking,
My mind turns straight to wine.

I hate bugs and errors.
But I just think back to wine,
And I'm happy once again.

I like to hang out with programming and deep learning.
But when left alone,
My mind turns straight to wine.
'''

In [3]:
tokens = raw_text.split()
raw_text = ' '.join(tokens)
print(raw_text)

I get on with life as a programmer, I like to contemplate beer. But when I start to daydream, My mind turns straight to wine. Do I love wine more than beer? I like to use words about beer. But when I stop my talking, My mind turns straight to wine. I hate bugs and errors. But I just think back to wine, And I'm happy once again. I like to hang out with programming and deep learning. But when left alone, My mind turns straight to wine.


In [4]:
char_vocab = sorted(list(set(raw_text)))
vocab_size = len(char_vocab)
print('문자 집합 :',char_vocab)
print('문자 집합의 크기 : {}'.format(vocab_size))

문자 집합 : [' ', "'", ',', '.', '?', 'A', 'B', 'D', 'I', 'M', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y']
문자 집합의 크기 : 33


In [5]:
char_to_index = dict((char,index) for index,char in enumerate(char_vocab))
print(char_to_index)

{' ': 0, "'": 1, ',': 2, '.': 3, '?': 4, 'A': 5, 'B': 6, 'D': 7, 'I': 8, 'M': 9, 'a': 10, 'b': 11, 'c': 12, 'd': 13, 'e': 14, 'f': 15, 'g': 16, 'h': 17, 'i': 18, 'j': 19, 'k': 20, 'l': 21, 'm': 22, 'n': 23, 'o': 24, 'p': 25, 'r': 26, 's': 27, 't': 28, 'u': 29, 'v': 30, 'w': 31, 'y': 32}


In [6]:
length = 11
sequences = []
for i in range(length,len(raw_text)):
    seq = raw_text[i-length:i]
    sequences.append(seq)
print('총 훈련 샘플의 수 : %d' % len(sequences))

총 훈련 샘플의 수 : 426


In [7]:
sequences[:10]

['I get on wi',
 ' get on wit',
 'get on with',
 'et on with ',
 't on with l',
 ' on with li',
 'on with lif',
 'n with life',
 ' with life ',
 'with life a']

In [10]:
encoded_sequences = []
for sequence in sequences:
    encoded_sequence = [char_to_index[char] for char in sequence]
    encoded_sequences.append(encoded_sequence)

In [11]:
encoded_sequences[:5]

[[8, 0, 16, 14, 28, 0, 24, 23, 0, 31, 18],
 [0, 16, 14, 28, 0, 24, 23, 0, 31, 18, 28],
 [16, 14, 28, 0, 24, 23, 0, 31, 18, 28, 17],
 [14, 28, 0, 24, 23, 0, 31, 18, 28, 17, 0],
 [28, 0, 24, 23, 0, 31, 18, 28, 17, 0, 21]]

In [12]:
encoded_sequences = np.array(encoded_sequences)
X_data = encoded_sequences[:,:-1]
y_data = encoded_sequences[:,-1]

In [13]:
print(X_data[:5])
print(y_data[:5])

[[ 8  0 16 14 28  0 24 23  0 31]
 [ 0 16 14 28  0 24 23  0 31 18]
 [16 14 28  0 24 23  0 31 18 28]
 [14 28  0 24 23  0 31 18 28 17]
 [28  0 24 23  0 31 18 28 17  0]]
[18 28 17  0 21]


In [14]:
X_data_one_hot = [to_categorical(encoded,num_classes=vocab_size) for encoded in X_data]
X_data_one_hot = np.array(X_data_one_hot)
y_data_one_hot = to_categorical(y_data,num_classes=vocab_size)

In [15]:
print(X_data_one_hot.shape)

(426, 10, 33)


In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences
hidden_units = 64

model = Sequential()
model.add(LSTM(hidden_units,input_shape=(X_data_one_hot.shape[1],X_data_one_hot.shape[2])))
model.add(Dense(vocab_size,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_data_one_hot,y_data_one_hot,epochs=100,verbose=2)

Epoch 1/100
14/14 - 2s - loss: 3.4656 - accuracy: 0.1432
Epoch 2/100
14/14 - 0s - loss: 3.3449 - accuracy: 0.2019
Epoch 3/100
14/14 - 0s - loss: 3.0599 - accuracy: 0.1972
Epoch 4/100
14/14 - 0s - loss: 3.0005 - accuracy: 0.1972
Epoch 5/100
14/14 - 0s - loss: 2.9586 - accuracy: 0.1972
Epoch 6/100
14/14 - 0s - loss: 2.9388 - accuracy: 0.1972
Epoch 7/100
14/14 - 0s - loss: 2.9376 - accuracy: 0.1972
Epoch 8/100
14/14 - 0s - loss: 2.9142 - accuracy: 0.1972
Epoch 9/100
14/14 - 0s - loss: 2.9023 - accuracy: 0.1972
Epoch 10/100
14/14 - 0s - loss: 2.8843 - accuracy: 0.1972
Epoch 11/100
14/14 - 0s - loss: 2.8579 - accuracy: 0.1972
Epoch 12/100
14/14 - 0s - loss: 2.8331 - accuracy: 0.1972
Epoch 13/100
14/14 - 0s - loss: 2.8091 - accuracy: 0.2019
Epoch 14/100
14/14 - 0s - loss: 2.7820 - accuracy: 0.1995
Epoch 15/100
14/14 - 0s - loss: 2.7520 - accuracy: 0.1995
Epoch 16/100
14/14 - 0s - loss: 2.7157 - accuracy: 0.2324
Epoch 17/100
14/14 - 0s - loss: 2.6828 - accuracy: 0.2488
Epoch 18/100
14/14 - 0s

In [23]:
def sentence_generation(model, char_to_index, seq_length, seed_text, n):

    # 초기 시퀀스
    init_text = seed_text
    sentence = ''

    # 다음 문자 예측은 총 n번만 반복.
    for _ in range(n):
        encoded = [char_to_index[char] for char in seed_text] # 현재 시퀀스에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=seq_length, padding='pre') # 데이터에 대한 패딩
        encoded = to_categorical(encoded, num_classes=len(char_to_index))

        # 입력한 X(현재 시퀀스)에 대해서 y를 예측하고 y(예측한 문자)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for char, index in char_to_index.items():
            if index == result:
                break

        # 현재 시퀀스 + 예측 문자를 현재 시퀀스로 변경
        seed_text = seed_text + char

        # 예측 문자를 문장에 저장
        sentence = sentence + char

    # n번의 다음 문자 예측이 끝나면 최종 완성된 문장을 리턴.
    sentence = init_text + sentence
    return sentence

In [24]:
print(sentence_generation(model,char_to_index,10,'I get on w',80))

I get on with life as a programmer, I like to contemplate beer. But when I start to daydre
