In [1]:
import pandas as pd
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

In [2]:
result = tokenizer.tokenize('Here is the sentence I want embeddings for.')
print(result)

['here', 'is', 'the', 'sentence', 'i', 'want', 'em', '##bed', '##ding', '##s', 'for', '.']


In [3]:
print(tokenizer.vocab['here'])

2182


In [4]:
print(tokenizer.vocab['embeddings'])

KeyError: 'embeddings'

In [5]:
print(tokenizer.vocab['em'])

7861


In [6]:
print(tokenizer.vocab['##bed'])

8270


In [7]:
print(tokenizer.vocab['##ding'])

4667


In [8]:
print(tokenizer.vocab['##s'])

2015


In [12]:
with open('vocabulary.txt','w',encoding='utf-8') as f:
    for token in tokenizer.vocab.keys():
        f.write(token + '\n')

# 에러 발생시  encoding='utf-8'로 해결

In [13]:
df = pd.read_fwf('vocabulary.txt', header=None)
df

0
0          [PAD]
1      [unused0]
2      [unused1]
3      [unused2]
4      [unused3]
...          ...
30517        ##．
30518        ##／
30519        ##：
30520        ##？
30521        ##～

[30522 rows x 1 columns]

In [14]:
print('단어 집합의 크기 :',len(df))

단어 집합의 크기 : 30522


In [15]:
df.loc[4667].values[0]

'##ding'

In [16]:
df.loc[102].values[0]

'[SEP]'

In [17]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

In [18]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased')
Tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')

All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-large-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [19]:
inputs = tokenizer('Soccer is a really fun [MASK].',return_tensors='tf')

In [20]:
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [21]:
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)


In [22]:
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [23]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model,tokenizer=tokenizer)

In [24]:
pip('Soccer is a really fun [MASK].')

[{'score': 0.7621114253997803,
  'token': 4368,
  'token_str': 's p o r t',
  'sequence': 'soccer is a really fun sport.'},
 {'score': 0.2034202218055725,
  'token': 2208,
  'token_str': 'g a m e',
  'sequence': 'soccer is a really fun game.'},
 {'score': 0.012208577245473862,
  'token': 2518,
  'token_str': 't h i n g',
  'sequence': 'soccer is a really fun thing.'},
 {'score': 0.0018630269914865494,
  'token': 4023,
  'token_str': 'a c t i v i t y',
  'sequence': 'soccer is a really fun activity.'},
 {'score': 0.0013354880502447486,
  'token': 2492,
  'token_str': 'f i e l d',
  'sequence': 'soccer is a really fun field.'}]

In [25]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.25628921389579773,
  'token': 2265,
  'token_str': 's h o w',
  'sequence': 'the avengers is a really fun show.'},
 {'score': 0.17284151911735535,
  'token': 3185,
  'token_str': 'm o v i e',
  'sequence': 'the avengers is a really fun movie.'},
 {'score': 0.11107736825942993,
  'token': 2466,
  'token_str': 's t o r y',
  'sequence': 'the avengers is a really fun story.'},
 {'score': 0.07248975336551666,
  'token': 2186,
  'token_str': 's e r i e s',
  'sequence': 'the avengers is a really fun series.'},
 {'score': 0.07046635448932648,
  'token': 2143,
  'token_str': 'f i l m',
  'sequence': 'the avengers is a really fun film.'}]

In [26]:
pip('I went to [MASK] this morning.')

[{'score': 0.35730719566345215,
  'token': 2147,
  'token_str': 'w o r k',
  'sequence': 'i went to work this morning.'},
 {'score': 0.23304477334022522,
  'token': 2793,
  'token_str': 'b e d',
  'sequence': 'i went to bed this morning.'},
 {'score': 0.12845076620578766,
  'token': 2082,
  'token_str': 's c h o o l',
  'sequence': 'i went to school this morning.'},
 {'score': 0.06230570003390312,
  'token': 3637,
  'token_str': 's l e e p',
  'sequence': 'i went to sleep this morning.'},
 {'score': 0.046952567994594574,
  'token': 2465,
  'token_str': 'c l a s s',
  'sequence': 'i went to class this morning.'}]

In [27]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

In [32]:
model = TFBertForMaskedLM.from_pretrained('klue/bert-base', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForMaskedLM: ['cls.predictions.decoder.bias', 'bert.embeddings.position_ids']
- This IS expected if you are initializing TFBertForMaskedLM from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForMaskedLM from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [33]:
inputs = tokenizer('축구는 정말 재미있는 [MASK]다.', return_tensors='tf')

In [34]:
print(inputs['input_ids'])

tf.Tensor([[   2 4713 2259 3944 6001 2259    4  809   18    3]], shape=(1, 10), dtype=int32)


In [35]:
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0 0]], shape=(1, 10), dtype=int32)


In [36]:
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1 1]], shape=(1, 10), dtype=int32)


In [37]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model,tokenizer=tokenizer)

In [38]:
pip('축구는 정말 재미있는 [MASK]다.')

[{'score': 0.8963505625724792,
  'token': 4559,
  'token_str': '스포츠',
  'sequence': '축구는 정말 재미있는 스포츠 다.'},
 {'score': 0.0259577464312315,
  'token': 568,
  'token_str': '거',
  'sequence': '축구는 정말 재미있는 거 다.'},
 {'score': 0.01003390271216631,
  'token': 3682,
  'token_str': '경기',
  'sequence': '축구는 정말 재미있는 경기 다.'},
 {'score': 0.00792438443750143,
  'token': 4713,
  'token_str': '축구',
  'sequence': '축구는 정말 재미있는 축구 다.'},
 {'score': 0.007844255305826664,
  'token': 5845,
  'token_str': '놀이',
  'sequence': '축구는 정말 재미있는 놀이 다.'}]

In [39]:
pip('어벤져스는 정말 재미있는 [MASK]다.')

[{'score': 0.8382408618927002,
  'token': 3771,
  'token_str': '영화',
  'sequence': '어벤져스는 정말 재미있는 영화 다.'},
 {'score': 0.028275631368160248,
  'token': 568,
  'token_str': '거',
  'sequence': '어벤져스는 정말 재미있는 거 다.'},
 {'score': 0.01718941703438759,
  'token': 4665,
  'token_str': '드라마',
  'sequence': '어벤져스는 정말 재미있는 드라마 다.'},
 {'score': 0.014989688992500305,
  'token': 3758,
  'token_str': '이야기',
  'sequence': '어벤져스는 정말 재미있는 이야기 다.'},
 {'score': 0.009382696822285652,
  'token': 4938,
  'token_str': '장소',
  'sequence': '어벤져스는 정말 재미있는 장소 다.'}]

In [40]:
pip('나는 오늘 아침에 [MASK]에 출근을 했다.')

[{'score': 0.08012586086988449,
  'token': 3769,
  'token_str': '회사',
  'sequence': '나는 오늘 아침에 회사 에 출근을 했다.'},
 {'score': 0.06124088913202286,
  'token': 1,
  'token_str': '[UNK]',
  'sequence': '나는 오늘 아침에 에 출근을 했다.'},
 {'score': 0.017486676573753357,
  'token': 4345,
  'token_str': '공장',
  'sequence': '나는 오늘 아침에 공장 에 출근을 했다.'},
 {'score': 0.016131803393363953,
  'token': 5841,
  'token_str': '사무실',
  'sequence': '나는 오늘 아침에 사무실 에 출근을 했다.'},
 {'score': 0.015360810793936253,
  'token': 3671,
  'token_str': '서울',
  'sequence': '나는 오늘 아침에 서울 에 출근을 했다.'}]

In [41]:
import tensorflow as tf
from transformers import TFBertForNextSentencePrediction
from transformers import AutoTokenizer

In [42]:
model = TFBertForNextSentencePrediction.from_pretrained('bert-base-uncased')
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

All model checkpoint layers were used when initializing TFBertForNextSentencePrediction.

All the layers of TFBertForNextSentencePrediction were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForNextSentencePrediction for predictions without further training.


In [43]:
prompt = "In Italy, pizza served in formal settings, such as at a restaurant, is presented unsliced."
next_sentence = "pizza is eaten with the use of a knife and fork. In casual settings, however, it is cut into wedges to be eaten while held in the hand."

In [44]:
encoding = tokenizer(prompt,next_sentence,return_tensors='tf')

In [45]:
print(encoding['input_ids'])

tf.Tensor(
[[  101  1999  3304  1010 10733  2366  1999  5337 10906  1010  2107  2004
   2012  1037  4825  1010  2003  3591  4895 14540  6610  2094  1012   102
  10733  2003  8828  2007  1996  2224  1997  1037  5442  1998  9292  1012
   1999 10017 10906  1010  2174  1010  2009  2003  3013  2046 17632  2015
   2000  2022  8828  2096  2218  1999  1996  2192  1012   102]], shape=(1, 58), dtype=int32)


In [46]:
print(tokenizer.cls_token,':',tokenizer.cls_token_id)
print(tokenizer.sep_token,':',tokenizer.sep_token_id)

[CLS] : 101
[SEP] : 102


In [47]:
print(tokenizer.decode(encoding['input_ids'][0]))

[CLS] in italy, pizza served in formal settings, such as at a restaurant, is presented unsliced. [SEP] pizza is eaten with the use of a knife and fork. in casual settings, however, it is cut into wedges to be eaten while held in the hand. [SEP]


In [48]:
print(encoding['token_type_ids'])

tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]], shape=(1, 58), dtype=int32)


In [49]:
logits = model(encoding['input_ids'],token_type_ids=encoding['token_type_ids'])[0]
softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print(probs)

tf.Tensor([[9.9999714e-01 2.8381858e-06]], shape=(1, 2), dtype=float32)


In [50]:
print('최종 예측 레이블 :', tf.math.argmax(probs, axis=-1).numpy())

최종 예측 레이블 : [0]


In [51]:
prompt = "In Italy, pizza served in formal settings, such as at a restaurant, is presented unsliced."
next_sentence = "The sky is blue due to the shorter wavelength of blue light."
encoding = tokenizer(prompt,next_sentence,return_tensors='tf')

logits = model(encoding['input_ids'],token_type_ids=encoding['token_type_ids'])[0]
softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print('최종 예측 레이블 :',tf.math.argmax(probs,axis=-1).numpy())

최종 예측 레이블 : [1]


In [52]:
import tensorflow as tf
from transformers import TFBertForNextSentencePrediction
from transformers import AutoTokenizer

In [53]:
model = TFBertForNextSentencePrediction.from_pretrained('klue/bert-base',from_pt=True)
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForNextSentencePrediction: ['bert.embeddings.position_ids']
- This IS expected if you are initializing TFBertForNextSentencePrediction from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForNextSentencePrediction from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForNextSentencePrediction were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForNextSentencePrediction for predictions without further training.


In [54]:
prompt = "2002년 월드컵 축구대회는 일본과 공동으로 개최되었던 세계적인 큰 잔치입니다."
next_sentence = "여행을 가보니 한국의 2002년 월드컵 축구대회의 준비는 완벽했습니다."
encoding = tokenizer(prompt,next_sentence,return_tensors='tf')
logits = model(encoding['input_ids'],token_type_ids=encoding['token_type_ids'])[0]
softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print('최종 예측 레이블 :',tf.math.argmax(probs,axis=-1).numpy())

최종 예측 레이블 : [0]


In [55]:
prompt = "2002년 월드컵 축구대회는 일본과 공동으로 개최되었던 세계적인 큰 잔치입니다."
next_sentence = "극장가서 로맨스 영화를 보고싶어요"
encoding = tokenizer(prompt, next_sentence, return_tensors='tf')

logits = model(encoding['input_ids'], token_type_ids=encoding['token_type_ids'])[0]

softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print('최종 예측 레이블 :', tf.math.argmax(probs, axis=-1).numpy())

최종 예측 레이블 : [1]
